// This file is part of ReLarn; Copyright (C) 1986 - 2018; GPLv2; NO WARRANTY!
// See Copyright.txt, LICENSE.txt and AUTHORS.txt for terms.

// Various non-monster-death game endings (most of which are bad)
ENDING(DDSELFANNIH,     "hit your own sphere of annhilation.")
ENDING(DDARROW,         "were shot by an arrow.")
ENDING(DDDART,          "were hit by a dart.")
ENDING(DDPIT,           "fell into a pit.")
ENDING(DDHELL,          "fell into a bottomless pit to HELL!")
ENDING(DDWINNER,        "won, saving your daughter.")
ENDING(DDENTOMBED,      "got trapped in solid rock.")
ENDING(DDTOOLATE,       "killed your family and yourself.")
ENDING(DDFINGER,        "were erased by a wayward finger")
ENDING(DDTRAPDOORHELL,  "fell through a bottomless trap door to HELL.")
ENDING(DDTRAPDOOR,      "fell through a trap door.")
ENDING(DDBADWATER,      "drank some poisonous water.")
ENDING(DDSHOCK,         "were fried by an electric shock.")
ENDING(DDSHAFT,         "slipped on a volcano shaft.")
ENDING(DDDEMON,         "were attacked by the demon you summoned.")
ENDING(DDMAGICOOPS,     "were hit by your own magic.")
ENDING(DDUNSEEN,        "were demolished by an unseen attacker.")
ENDING(DDSLEEP,         "fell into the dreadful sleep.")
ENDING(DDCHEST,         "were killed by an exploding chest.")
ENDING(DDSPHERE,        "were killed by exploding sphere of annihilation.")
ENDING(DDGENIE,         "pissed off a genie.")
ENDING(DDHELLEVATOR,    "took an elevator straight to HELL!!!")
